service: screenshot-service2
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1

functions:
  capture:
    handler: handler.capture # refers to function capture in index.js
    events:
      - http: # trigger function via http request
          path: capture
          method: post
    memorySize: 1536 # RAM size for the function
    timeout: 15
