MAX_NUMBER_INVOCATION_ATTEMPTS = 5
ACCEPTED_MEMORY_RANGE_AWS = (128, 3008)
TOTAL_SAMPLE_COUNT = 10
TERMINATION_CV = 0.05
DYNAMIC_SAMPLING_MAX = 3
DYNAMIC_SAMPLING_INITIAL_STEP = 2
TERMINATION_THRESHOLD = 3
